version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_DB=console_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/console_db
      - JWT_SECRET=supersecret
      - NEXT_PUBLIC_MAP_STYLE=https://demotiles.maplibre.org/style.json
    ports:
      - '3000:3000'
    command: npm start

volumes:
  db_data: 